### ISSUE TITLE
Feature Requests: swap movement/camera, invert camera Y-axis, enable stereoscopic 3D

### ISSUE THREAD

**Issue by vaguerant** [LiquidFenrir/MineSweeper3D#1]
No actual issues to report, just a few things I'd personally like to see. These are all things I think would be best implemented as options for the end-user, not forced on everybody.

1. **Swap movement and camera inputs**
Personally, I'd find it more natural to move using the left-hand inputs (D-Pad/Circle Pad) and move the camera with the right-hand inputs (face buttons/C-Stick).
2. **Invert camera Y-axis**
Some of us old types grew up on flight sims and stuff and we're used to the kind of camera controls where pressing down points the nose upward and vice versa. Nice to have, obviously not essential.
3. **Enable stereoscopic 3D**
It's minesweeper in 3D, but without the 3D! If you're going to take a traditionally 2D game and rework it in 3D, with 3D in the title, on the 3DS, you have to include 3D stereoscopy in there!

Anyway, whether or not you implement any of these features, thanks for the game!

**Comment by vaguerant** [comment]
Fantastic stuff, the control options are great and the 3D looks awesome.

Unfortunately, adding stereoscopy seems to have introduced a bug with the title screen where only one eye's framebuffer is being filled with the title screen while the other is just "whatever was in there before", so each eye is receiving a different image simultaneously.

Screenshots:
![nclFy8R](https://user-images.githubusercontent.com/5259025/84347093-01937680-abf5-11ea-8fe9-b13149d801b2.png)
![nUAiMmq](https://user-images.githubusercontent.com/5259025/84347092-00fae000-abf5-11ea-9be6-7ee16452c134.png)
When you first start up the game, the second framebuffer is empty, so you're seeing the title screen in one eye and black in the other.

![nclFy8R](https://user-images.githubusercontent.com/5259025/84347093-01937680-abf5-11ea-8fe9-b13149d801b2.png)
![j576qXY](https://user-images.githubusercontent.com/5259025/84347091-ffc9b300-abf4-11ea-9872-1445943a68d3.png)
After returning to the title screen, the second framebuffer is still displaying the previous game state.

**Comment by LiquidFenrir** [comment]
Thanks for the report, it's fixed with 87a28d7 :)
