### ISSUE TITLE
Game crash with large levels/high mine counts

### ISSUE THREAD

**Issue by vaguerant** [LiquidFenrir/MineSweeper3D#2]
I tried ramping up the number of mines to make the game a bit more difficult, but there seem to be a couple of problems with the mine percentages. I'm not sure if these issues are related, but the first thing I noticed was there are less mines than there should be, e.g. if I play 10x10 with 40% mines, the resulting game only has 2 mines, and if I play 99x99 (that's 9801 tiles) and 40% mines, the result is only 245 mines, or ~2.5%.

In the process of testing this, I noticed something much more pressing: the whole system crashes when playing with 40% mines at larger sizes. Quickly testing different sizes to see when things start causing trouble:

- 50x50 40%: crash
- 37x37 40%: crash
- 34x34 40%: crash
- 33x33 40%: no crash
- 32x32 40%: no crash
- 31x31 40%: no crash
- 25x25 40%: no crash

Possibly some kind of overflow situation or something? Here's a photo of the Luma3DS crash screen that appears:
![IMG_20200611_230607_hdr](https://user-images.githubusercontent.com/5259025/84390355-cb78e580-ac3a-11ea-9f29-7dad76da8bf8.jpg)

**Comment by LiquidFenrir** [comment]
Oh, that's bad.  
For the mine count, I forgot how to do a proper percentage lol, but for the crash I'll need to research a bit more.  
Thanks a lot for the report! It should be fixed soon, I hope.

**Comment by LiquidFenrir** [comment]
I couldn't reproduce the crash, but I did notice a problem with the bomb/flag counter, so I added an extra digit (up to 9999, which works perfectly with the 99x99 limit). both should be fixed now

**Comment by vaguerant** [comment]
Yep, all fixed, no crashes even at maximum size and mine count. Great stuff, thanks!
